name: test_appbar_animation
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  # percent_indicator: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
